name: i18n_extension
description: Translation and Internationalization (i18n) for Flutter. Easy to use for both large and small projects. Uses Dart extensions to reduce boilerplate.
version: 4.0.2
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/i18n_extension

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sprintf: ^6.0.0
  args: ^1.6.0
  analyzer: ^1.1.0
  gettext_parser: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
