name: i18n_extension
description: Translation and Internationalization (i18n) for Flutter. Easy to use for both large and small projects. Uses Dart extensions to reduce boilerplate.
version: 5.0.0
homepage: https://github.com/marcglasberg/i18n_extension
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  sprintf: ^6.0.0
  args: ^2.3.0
  analyzer: ^4.2.0
  gettext_parser: ^0.2.0
  equatable: ^2.0.3
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

